//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Curso.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SysDesarrolloHEntities : DbContext
    {
        public SysDesarrolloHEntities()
            : base("name=SysDesarrolloHEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Ct_Plaza> Ct_Plaza { get; set; }
        public virtual DbSet<Ct_NivelCursos> Ct_NivelCursos { get; set; }
        public virtual DbSet<Tb_UsuariosCurso> Tb_UsuariosCurso { get; set; }
        public virtual DbSet<Ct_ActivoCursos> Ct_ActivoCursos { get; set; }
    }
}
