//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Curso.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Tb_UsuariosCurso
    {
        public int Int_IdUsuario { get; set; }
        public string Txt_Usuario { get; set; }
        public string Txt_Password { get; set; }
        public int Int_IdGerente { get; set; }
        public string Txt_Gerente { get; set; }
        public string Txt_Email { get; set; }
        public int Int_IdPlaza { get; set; }
        public int Int_IdNivel { get; set; }
       
        public DateTime ? Fec_Inicio { get; set; }
        [DataType(System.ComponentModel.DataAnnotations.DataType.Date)]
        public DateTime ? Fec_Fin { get; set; }
        public int Bol_Activo { get; set; }
    }
}
